/**
 * Sync Schemas Script
 * Aggregates all module schemas into central schemas.js file
 * 
 * This ensures schemas.js is always in sync with module schemas
 * Run this script whenever you update a module schema
 */

const fs = require('fs');
const path = require('path');

const MODULES_DIR = path.join(__dirname, '../src/modules');
const SCHEMAS_FILE = path.join(__dirname, '../src/schemas.js');

function findSchemaFiles() {
  const schemaFiles = [];
  
  function walkDir(dir) {
    const files = fs.readdirSync(dir);
    
    for (const file of files) {
      const filePath = path.join(dir, file);
      const stat = fs.statSync(filePath);
      
      if (stat.isDirectory()) {
        walkDir(filePath);
      } else if (file.endsWith('.schema.js')) {
        schemaFiles.push(filePath);
      }
    }
  }
  
  walkDir(MODULES_DIR);
  return schemaFiles;
}

function extractTableName(schemaPath) {
  const content = fs.readFileSync(schemaPath, 'utf8');
  const tableNameMatch = content.match(/TABLE_NAME\s*=\s*['"]([^'"]+)['"]/);
  return tableNameMatch ? tableNameMatch[1] : null;
}

function generateSchemasFile() {
  const schemaFiles = findSchemaFiles();
  const schemas = {};
  
  console.log(`📋 Found ${schemaFiles.length} schema files`);
  
  for (const schemaPath of schemaFiles) {
    try {
      const schemaModule = require(schemaPath);
      const tableName = schemaModule.TABLE_NAME || extractTableName(schemaPath);
      
      if (!tableName) {
        console.warn(`⚠️  Skipping ${schemaPath} - no TABLE_NAME found`);
        continue;
      }
      
      schemas[tableName] = {
        table: tableName,
        createTable: schemaModule.CREATE_TABLE || '',
        createIndexes: schemaModule.CREATE_INDEXES || ''
      };
      
      console.log(`   ✅ Processed: ${tableName}`);
    } catch (error) {
      console.error(`   ❌ Error processing ${schemaPath}:`, error.message);
    }
  }
  
  // Generate the schemas.js file content
  // Properly escape SQL strings for JavaScript
  const schemasString = Object.entries(schemas)
    .map(([key, value]) => {
      const createTable = (value.createTable || '').replace(/`/g, '\\`').replace(/\${/g, '\\${');
      const createIndexes = (value.createIndexes || '').replace(/`/g, '\\`').replace(/\${/g, '\\${');
      return `  ${key}: {
    table: ${JSON.stringify(value.table)},
    createTable: ${JSON.stringify(createTable)},
    createIndexes: ${JSON.stringify(createIndexes)}
  }`;
    })
    .join(',\n');

  const fileContent = `/**
 * Database Schemas
 * Auto-generated from module schemas
 * 
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * Run "npm run schemas:sync" to regenerate from module schemas
 * 
 * This file contains all table schemas aggregated from individual module schemas.
 * Used for:
 * - Database migration reference
 * - Model validation
 * - Schema documentation
 * 
 * @module schemas
 * @generated ${new Date().toISOString()}
 */

const schemas = {
${schemasString}
};

module.exports = schemas;
`;
  
  fs.writeFileSync(SCHEMAS_FILE, fileContent);
  console.log(`\n✅ Generated schemas.js with ${Object.keys(schemas).length} schemas`);
  console.log(`   File: ${SCHEMAS_FILE}`);
}

// Run the script
generateSchemasFile();
